create database sistemaHamburgueriaMG;
use sistemaHamburgueriaMG;


CREATE TABLE TB_FUNCIONARIO (
	ID_FUNCIONARIO	INT PRIMARY KEY AUTO_INCREMENT,
    DS_EMAIL		VARCHAR(100),
    DS_SENHA		VARCHAR(40)
);


CREATE TABLE TB_RESERVA (
	ID_RESERVA		INT PRIMARY KEY AUTO_INCREMENT,
    ID_FUNCIONARIO	INT,
    NR_MESA			INT,
    NM_CLIENTE		VARCHAR(300),
    QTD_PESSOAS		INT,
    DT_RESERVAS		DATE,
    DS_OBSERVACAO	VARCHAR(1000),
	FOREIGN KEY (ID_FUNCIONARIO) REFERENCES TB_FUNCIONARIO (ID_FUNCIONARIO)
);
